### PR TITLE
This implements the UserLegislatorInfo component that will form the persistent side panel of the app.

### PR DESCRIPTION
**Pull request by sscchan**
This implements the UserLegislatorsInfo & related subcomponent to display the user's house representative as well as senators.

The data is fetched from the Sunlight Congress API based on a given location (Lat and Long).

The temporary front page is modify to display a demo of the component.

### CODE REVIEW

**Review by cbathgate — COMMENTED** [review]
Very impressed with the amount of info for each rep. In the future, this will be implemented in sidebar format, correct? 

One thing worth noting for server-side: in order for data to fetch on my end, I changed the port to 8080. Did anybody else experience this when testing the code?

**Comment by sscchan** [comment]
I had an issue with the server not accepting the CORS request because the source was localhost:8080 but the URL on the browser is 127.0.0.1:8080, does the console / network tab in the developer tool say something similar in your browser?

**Comment by sscchan** [comment]
Yes this component will serve as the sidebar in the complete app. I used bootstrap which drives its' behaviour of expending to fit the full screen width.

**Comment by cbathgate** [comment]
yeah that was what my developer tools said as well. good to know. I will wait for benze to take a look  at it before merging

**Comment by benzeg** [comment]
port was initially set to 4568. 
" source was localhost:8080 but the URL on the browser is 127.0.0.1:8080" - not quite understanding this part, can you elaborate?

**Comment by sscchan** [comment]
@benzeg Request with CORS headers has a specific "origin" header where it states the domain where the call was being made from. In this case, it is localhost:8080 (what's on the browser URL bar). This is what the requester "claims" to be.

I believe the Sunlight foundation checks the "origin" field agains the ip address to verify that the "origin" field is not faked, and reject requests with a 400 error if they don't match.

For example, this will prevent a requester from claiming the origin is from dog.com, but in reality, the page initiating the request is actually evilcat.com. 

In our case, "localhost" is a hostname that resolves to 127.0.0.1, I believe we may be sending the Sunlight servers with mismatching header info. If you change the URL in the broswer to 127.0.0.1 the server will provide the expected response because the CORS header is now consistent.

**Comment by sscchan** [comment]
@benzeg I still running webpack-dev-server for testing purposes, it picks :8080 as the default port to listen to. Hence the different port compare to our real server at :4568.

**Review by benzeg — APPROVED** [review]

**Pull request merged**
